import test from 'node:test'
import assert from 'node:assert/strict'
import { campaignState } from '../src/campaign.js'
import { autonomousProgressionDecision, execute } from '../src/actions.js'
test('campaign advances through verified resources', () => { const state = campaignState({ inventory: { oak_log: 6, bread: 8, iron_ingot: 4 } }, []); assert.equal(state.phase, 'nether_prep'); assert.match(state.objective, /portale/i) })
test('campaign counts caught fish as food and a reusable resource', () => { const state = campaignState({ inventory: { oak_log: 4, cod: 8 } }, []); assert.equal(state.resources.food, 8); assert.equal(state.resources.fish, 8) })
test('campaign recognizes stronghold and end assault', () => { const state = campaignState({ inventory: { blaze_rod: 6, ender_pearl: 6, ender_eye: 5, iron_sword: 1 } }, [{ type: 'other', label: 'stronghold' }]); assert.equal(state.phase, 'end_assault'); assert.equal(state.completion, 95) })
test('campaign enters completed phase after a recorded dragon victory',()=>{const state=campaignState({inventory:{}},[{type:'victory',label:'Drago End sconfitto'}]);assert.equal(state.phase,'completed');assert.equal(state.completion,100)})
test('completed campaign offers role-aware challenges instead of stopping',()=>{const state=campaignState({inventory:{}},[{type:'victory',label:'Drago End sconfitto'}]);assert.ok(state.postVictoryChallenges.some(x=>x.id==='redstone'));assert.ok(state.postVictoryChallenges.every(x=>Array.isArray(x.roles)&&x.roles.length>0))})
test('activate_end_portal fills reachable frames and verifies portal block', async()=>{const frames=Array.from({length:12},(_,i)=>({name:'end_portal_frame',position:{x:i,y:30,z:0},getProperties:()=>({eye:false})}));let activated=0;const bot={inventory:{items:()=>[{name:'ender_eye',count:12}]},findBlocks:()=>frames.map(frame=>frame.position),blockAt:position=>frames.find(frame=>frame.position.x===position.x)||{name:'air'},findBlock:()=>activated>=12?{name:'end_portal',position:{x:0,y:30,z:0}}:null,equip:async()=>{},activateBlock:async()=>{activated++},pathfinder:{goto:async()=>{}},game:{dimension:'overworld'}};const result=await execute(bot,{action:'activate_end_portal',args:{}});assert.match(result,/portale End attivato/);assert.equal(activated,12)})
test('planner crafts Eyes of Ender when blaze powder and pearls are ready',()=>{const bot={inventory:{items:()=>[{name:'crafting_table',count:1},{name:'stone_pickaxe',count:1},{name:'stone_axe',count:1},{name:'chest',count:1},{name:'furnace',count:1},{name:'cobblestone',count:8},{name:'oak_log',count:2},{name:'blaze_powder',count:4},{name:'ender_pearl',count:4}]},findBlock:()=>null,registry:{blocksByName:{}}};const decision=autonomousProgressionDecision(bot,{health:20,food:20,nearbyEntities:[],nearbyBlocks:[]},[]);assert.equal(decision.action,'craft');assert.equal(decision.args.name,'ender_eye')})
test('planner converts blaze rods into powder before End preparation',()=>{const bot={inventory:{items:()=>[{name:'crafting_table',count:1},{name:'stone_pickaxe',count:1},{name:'stone_axe',count:1},{name:'chest',count:1},{name:'furnace',count:1},{name:'cobblestone',count:8},{name:'oak_log',count:2},{name:'blaze_rod',count:2},{name:'ender_pearl',count:4}]},findBlock:()=>null,registry:{blocksByName:{}}};const decision=autonomousProgressionDecision(bot,{health:20,food:20,nearbyEntities:[],nearbyBlocks:[]},[]);assert.equal(decision.action,'craft');assert.equal(decision.args.name,'blaze_powder')})
