import test from 'node:test'
import assert from 'node:assert/strict'
import { Vec3 } from 'vec3'
import { observe } from '../src/observe.js'

test('wide perception returns strategic targets and distant entities with coordinates',()=>{const p=new Vec3(0,64,0),blocks=new Map([['2,64,0','grass_block'],['40,64,0','diamond_ore']]),positions=[new Vec3(2,64,0),new Vec3(40,64,0)],bot={entity:{position:p},health:20,food:20,oxygenLevel:20,game:{dimension:'overworld',serverViewDistance:10},time:{timeOfDay:0},inventory:{items:()=>[],slots:[]},heldItem:null,entities:{cow:{name:'cow',type:'mob',position:new Vec3(35,64,0)}},findBlocks:options=>positions.filter(pos=>{const block={name:blocks.get(`${pos.x},${pos.y},${pos.z}`)};return options.matching(block)&&pos.distanceTo(p)<=options.maxDistance}).slice(0,options.count),blockAt:pos=>({name:blocks.get(`${pos.x},${pos.y},${pos.z}`)||'stone'})};const state=observe(bot,{visionRadius:48});assert.equal(state.vision.radiusBlocks,48);assert.equal(state.visibleTargets[0].name,'diamond_ore');assert.equal(state.visibleTargets[0].x,40);assert.equal(state.nearbyEntities[0].name,'cow');assert.equal(state.nearbyEntities[0].distance,35)})

test('observation preserves player username for social interaction',()=>{const p=new Vec3(0,64,0),bot={entity:{position:p},health:20,food:20,oxygenLevel:20,game:{},time:{timeOfDay:0},inventory:{items:()=>[],slots:[]},heldItem:null,entities:{player:{username:'Alex',type:'player',position:new Vec3(2,64,0)}},findBlocks:()=>[],blockAt:()=>({name:'stone'})};const state=observe(bot);assert.equal(state.nearbyEntities[0].username,'Alex')})

test('observation exposes fluid occupancy for emergency escape',()=>{const p=new Vec3(0,64,0),bot={entity:{position:p},health:20,food:20,oxygenLevel:20,game:{},time:{timeOfDay:0},inventory:{items:()=>[],slots:[]},heldItem:null,entities:{},findBlocks:()=>[],blockAt:pos=>({name:pos.y===64?'water':'stone'})};const state=observe(bot);assert.equal(state.feetBlock,'water');assert.equal(state.inFluid,true)})
