export const knowledge = [
  'Early game: collect logs, craft planks and a crafting table, then wooden and stone tools. Secure food and shelter before risky exploration.',
  'Wood search skill: do not request generic log or wood block names. Use collect_wood to accept every overworld log and Nether stem. If no tree is loaded, explore 16-30 blocks, scan again, and repeat without claiming success.',
  'Crafting dependency skill: one log normally yields four matching planks; four planks yield one crafting_table in the 2x2 inventory grid. The craft action can automatically produce craftable intermediate ingredients.',
  'Starter crafting skill: use exact item ids. crafting_table costs 4 matching planks. wooden_axe costs 3 planks plus 2 sticks and needs a placed crafting table. chest costs 8 matching planks and needs a crafting table. A colored bed costs 3 planks plus 3 wool of the same color and needs a crafting table. The craft action accepts workbench, plank/planks, axe, bed and container aliases, selects available wood or wool, creates intermediate items, places a crafting table when needed, and uses it.',
  'General crafting skill: the deterministic craft engine can use every normal registered inventory or crafting-table recipe in the connected Minecraft version. Generic names for pickaxe, axe, shovel, hoe and sword choose the strongest affordable material; wood-family objects choose an available plank species; beds choose available wool color. Exact ids remain preferred. Furnaces, shields, buckets, torches, doors, boats, signs, fences, trapdoors, slabs, stairs, ladders, bows, arrows, fishing rods and armor pieces are supported when their ingredients exist.',
  'Storage skill: remember coordinates of chests, trapped chests, and barrels. Use inspect_storage to update the last known contents before planning resource collection. Share useful storage locations with nearby teammates.',
  'Team skill: bots within 32 blocks exchange live inventory summaries, visible block types and goals. Persistent team checkpoints are shared across the whole server and survive restarts. Publish useful coordinates for chests, mines, dungeons, special monsters, resources, dangers, portals and bases; use move_to with checkpoint coordinates to coordinate work.',
  'Iron progression: mine iron ore, smelt it in a furnace, prioritize a shield, iron pickaxe, bucket, armor, and flint and steel.',
  'Diamond ore requires an iron or better pickaxe. Obsidian requires a diamond or netherite pickaxe. A Nether portal frame needs at least 10 obsidian.',
  'Nether progression: wear one gold armor piece around piglins. Find a fortress, defeat blazes, and collect blaze rods. Avoid fighting when low on health or food.',
  'Eyes of Ender are crafted from ender pearls and blaze powder. Carry extras because thrown eyes can break. Follow them to a stronghold and locate the portal room.',
  'End preparation: bring strong armor, a bow and arrows, food, blocks, water, and a carved pumpkin if desired. Destroy end crystals before attacking the dragon.',
  'If an action repeatedly fails, change approach: get closer, obtain the correct tool, gather prerequisites, or choose a safer reachable target.'
]
