import fs from 'node:fs/promises'
import path from 'node:path'
import { Vec3 } from 'vec3'
const solid=b=>b&&!/^(air|cave_air|void_air)$/.test(b.name||'')
export function classifyPoi(name=''){if(/^(chest|trapped_chest|barrel)$/.test(name))return'storage';if(/portal|end_gateway/.test(name))return'portal';if(/lava|fire|spawner|magma/.test(name))return'danger';if(/(_ore|ancient_debris)$/.test(name))return'resource';if(/crafting_table|furnace|smoker|anvil|enchanting_table|brewing_stand|stonecutter|grindstone/.test(name))return'workstation';return null}
export class WorldMapMemory{
  constructor(file,cellSize=4){this.file=file;this.cellSize=cellSize;this.cells={};this.trail=[];this.pois={};this.landmarks={}}
  async load(){try{const data=JSON.parse(await fs.readFile(this.file,'utf8'));this.cells=data.cells||{};this.trail=data.trail||[];this.pois=data.pois||{};this.landmarks=data.landmarks||{}}catch{}}
  async save(){await fs.mkdir(path.dirname(this.file),{recursive:true});await fs.writeFile(this.file,JSON.stringify({cellSize:this.cellSize,cells:this.cells,trail:this.trail,pois:this.pois,landmarks:this.landmarks},null,2))}
  rememberTargets(targets=[],dimension='overworld'){const now=new Date().toISOString();for(const target of targets){if(!target?.name||![target.x,target.y,target.z].every(Number.isFinite))continue;const gx=Math.floor(target.x/8),gz=Math.floor(target.z/8),key=`${dimension}:${target.name}:${gx},${gz}`,old=this.landmarks[key];this.landmarks[key]={name:target.name,x:Math.floor(target.x),y:Math.floor(target.y),z:Math.floor(target.z),dimension,category:classifyPoi(target.name)||(/log|wood|stem|hyphae|leaves|wool/.test(target.name)?'resource':'landmark'),firstSeen:old?.firstSeen||now,lastSeen:now,sightings:(old?.sightings||0)+1}}const entries=Object.entries(this.landmarks);if(entries.length>1000)for(const [key] of entries.sort((a,b)=>String(a[1].lastSeen).localeCompare(String(b[1].lastSeen))).slice(0,entries.length-1000))delete this.landmarks[key]}
  knowledge(position,dimension='overworld',limit=80){const p=position||{x:0,z:0},cells=Object.values(this.cells),terrain=new Map();for(const cell of cells)terrain.set(cell.block,(terrain.get(cell.block)||0)+1);const rememberedLocations=[...Object.values(this.landmarks),...Object.values(this.pois).map(x=>({...x,dimension:x.dimension||'overworld',sightings:x.sightings||1}))].filter(x=>(x.dimension||'overworld')===dimension).map(x=>({...x,distance:Math.round(Math.hypot(x.x-p.x,x.z-p.z))})).sort((a,b)=>a.distance-b.distance).slice(0,limit);const xs=cells.map(x=>x.x*this.cellSize),zs=cells.map(x=>x.z*this.cellSize);return{dimension,exploredCells:cells.length,bounds:cells.length?{minX:Math.min(...xs),maxX:Math.max(...xs),minZ:Math.min(...zs),maxZ:Math.max(...zs)}:null,terrainTypes:[...terrain].sort((a,b)=>b[1]-a[1]).slice(0,12).map(([name,count])=>({name,cells:count})),rememberedLocations}}
  async sample(bot,visionRadius=48){if(!bot?.entity)return;const p=bot.entity.position,cx=Math.floor(p.x/this.cellSize),cz=Math.floor(p.z/this.cellSize),baseY=Math.floor(p.y),cellRadius=Math.max(3,Math.min(10,Math.ceil((Number(visionRadius)||48)/this.cellSize)));for(let x=cx-cellRadius;x<=cx+cellRadius;x++)for(let z=cz-cellRadius;z<=cz+cellRadius;z++){let found=null;for(let y=baseY+4;y>=baseY-12;y--){const b=bot.blockAt(new Vec3(x*this.cellSize+2,y,z*this.cellSize+2));if(solid(b)){found=b;break}}const key=`${x},${z}`,old=this.cells[key];this.cells[key]={x,z,y:found?.position?.y??old?.y??baseY,block:found?.name||old?.block||'unknown',firstSeen:old?.firstSeen||new Date().toISOString(),lastSeen:new Date().toISOString(),visits:(old?.visits||0)+(x===cx&&z===cz?1:0)}}if(typeof bot.findBlocks==='function'){const positions=bot.findBlocks({matching:b=>!!classifyPoi(b?.name),maxDistance:Math.min(Number(visionRadius)||48,64),count:160});for(const pos of positions){const b=bot.blockAt(pos),category=classifyPoi(b?.name);if(!category)continue;const key=`${Math.floor(pos.x)},${Math.floor(pos.y)},${Math.floor(pos.z)}`;this.pois[key]={x:Math.floor(pos.x),y:Math.floor(pos.y),z:Math.floor(pos.z),name:b.name,category,lastSeen:new Date().toISOString()}}}const point={x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z),at:new Date().toISOString()};const last=this.trail.at(-1);if(!last||last.x!==point.x||last.z!==point.z)this.trail.push(point);if(this.trail.length>5000)this.trail.splice(0,this.trail.length-5000);await this.save()}
  data(position,chests=[]){return{cellSize:this.cellSize,cells:Object.values(this.cells),trail:this.trail.slice(-2000),position:position?{x:Math.floor(position.x),y:Math.floor(position.y),z:Math.floor(position.z)}:null,chests,pois:Object.values(this.pois),landmarks:Object.values(this.landmarks)}}
}
